# Generated by Django 3.1 on 2020-09-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200903_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetail',
            name='fathers_signature',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='mothers_signature',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='name',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='occupation',
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='authorized_by',
            field=models.CharField(default=None, max_length=275),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='fathers_occupation',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='mothers_occupation',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='student_code',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
