# Generated by Django 3.1 on 2020-09-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200903_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dateofbirth',
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=16),
        ),
    ]
