# Generated by Django 3.1 on 2020-09-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20200905_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=10)),
                ('dateofbirth', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='media/students/%Y/%m/%d/')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
    ]
