# Generated by Django 3.1 on 2020-09-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersdetail',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/teacher/%Y/%m/%d/'),
        ),
    ]
